apiVersion: v1
kind: Service
metadata:
  name: headlamp
  labels:
    app: headlamp
spec:
  type: NodePort
  selector:
    app: headlamp
  ports:
  - port: 4466
    targetPort: 4466
    nodePort: 30081
